- name: Setup mini PC
  hosts: all
  become: false

  vars_files:
    - vars/secrets.yml

  tasks:
  - name: Setup cloudflared
    ansible.builtin.import_tasks: tasks/cloudflared.yml

  - name: Setup plant-diary
    ansible.builtin.import_tasks: tasks/plant-diary.yml
